import { Note } from "../redux/notes/types";

export const initialNotes: Note[] = [
    {
    id: 1,
    img: "/images/idea.png",
    name: "Creative Time",
    created: "2023-08-01",
    category: "Personal",
    content: "Sketch or paint for at least 45 minutes",
    date: "2023-08-01",
    archived: false,
  },
  {
    id: 2,
    img: "/images/loupe.png",
    name: "Call and Connect",
    created: "2023-08-02",
    category: "Work",
    content: "Review and respond to emails after lunch.",
    date: "2023-08-02",
    archived: false,
  },
  {
    id: 3,
    img: "/images/planet-earth.png",
    name: "Home Organization",
    created: "2023-08-03",
    category: "Personal",
    content: "Declutter the living room shelves.",
    date: "2023-08-03",
    archived: false,
  },
  {
    id: 4,
    img: "/images/shopping-basket.png",
    name: "Work Tasks",
    created: "2023-08-04",
    category: "Work",
    content: "Schedule a meeting with the marketing team",
    date: "2023-08-04",
    archived: false,
  },
  {
    id: 5,
    img: "/images/yoga-pose.png",
    name: "Personal Goals",
    created: "2023-08-05",
    category: "Personal",
    content: "Practice meditation for 15 minutes.",
    date: "2023-08-05",
    archived: false,
  },
  {
    id: 6,
    img: "/images/shopping-basket.png",
    name: "Note 6",
    created: "2023-08-06",
    category: "Work",
    content: "This is the content of Note 6.",
    date: "2023-08-06",
    archived: false,
  },
  {
    id: 7,
    img: "/images/idea.png",
    name: "Personal Goals",
    created: "2023-08-07",
    category: "Personal",
    content: "Go for a 30-minute jog in the morning.",
    date: "2023-08-07",
    archived: false,
  }];